source("R/D-estimations/D1-estimation_brute.R")
source("R/D-estimations/D2-valeur_reelle.R")
source("R/D-estimations/D3-estimation_flash.R")
source("R/D-estimations/D4-estimations_MC.R")
source("R/D-estimations/D5-run_simulations_MC.R")
